
/**
 * The import list can be semi-auto generated by running the following command:
 *   find node_modules/lighthouse/typings/**.d.ts | \
 *     sed -E "s#node_modules/(lighthouse/typings)/(.*).d.ts#import \2 = require('\1/\2');#g"
 */

// Lighthouse imports
import artifacts = require('lighthouse/typings/artifacts');
import audit = require('lighthouse/typings/audit');
import config = require('lighthouse/typings/config');
import crdpMapping = require('lighthouse/typings/crdp-mapping');
import externs = require('lighthouse/typings/externs');
import gatherer = require('lighthouse/typings/gatherer');
import htmlRenderer = require('lighthouse/typings/html-renderer');
import lhr = require('lighthouse/typings/lhr');
import lhrLite = require('lighthouse/typings/lhr-lite');
import protocol = require('lighthouse/typings/protocol');
import webInspector = require('lighthouse/typings/web-inspector');

declare global {
  export interface AdsArtifacts {
    numRequests: number;
    numImpressions: number;
  }

  export interface Artifacts extends LH.Artifacts {
    RenderedAdSlots?: Array<LH.Crdp.DOM.BoxModel | null>;
    StaticAdTags?: Array<LH.Crdp.DOM.Node>;
    Ads?: AdsArtifacts;
  }
}
