name: Link checker

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Link checker
        uses: lycheeverse/lychee-action@v1.1.0
        with:
          args: --verbose --no-progress --exclude-file=.lycheeignore **/*.md **/audits/*.js
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create issue from file
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link checker report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
